version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    hostname: postgres_privileges
    container_name: postgres_privileges_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5444:5432