sonar.projectKey=AntaresSimulatorTeam_antares-datamanager-back
sonar.organization=antaressimulatorteam
sonar.host.url=https://sonarcloud.io
sonar.login=2bc966dd270c9454aab5f0a892e2334377a14a99
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.language=java
sonar.sourceEncoding=UTF-8

